name: Rust

on:
  push:
    branches: [ "feature", "bugfix" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: |
        cargo check
        cargo clippy
        cargo check --tests
        cargo clippy --tests
        cargo check --examples
        cargo clippy --examples
    - name: Run tests
      run: cargo test
